-- MySQL Script generated by MySQL Workbench
-- Tue Jul 24 21:59:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estruturart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estruturart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estruturart` DEFAULT CHARACTER SET utf8 ;
USE `estruturart` ;

-- -----------------------------------------------------
-- Table `estruturart`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uf` VARCHAR(2) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado_id` INT NOT NULL,
  `uf` VARCHAR(4) NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `estruturart`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`status_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`status_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_pessoa` ENUM('Pessoa física', 'Pessoa Jurídica') NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `cpf_cnpj` VARCHAR(19) NOT NULL,
  `rg_inscricao_estadual` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `codigo` VARCHAR(10) NULL,
  `senha` VARCHAR(60) NULL,
  `perfil_id` INT NOT NULL,
  `status_usuario_id` INT NOT NULL,
  `data_inclusao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_id` ASC),
  INDEX `fk_usuario_status_usuario1_idx` (`status_usuario_id` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `estruturart`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_status_usuario1`
    FOREIGN KEY (`status_usuario_id`)
    REFERENCES `estruturart`.`status_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`status_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`status_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caminho_arquivo_nota_fiscal` TEXT NULL,
  `data_inclusao` DATE NOT NULL,
  `data_previsao_instalacao` DATE NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `valor_mao_obra` FLOAT NULL,
  `pedido_pago` INT(1) NULL DEFAULT 0,
  `observacao` TEXT NULL,
  `usuario_id` INT NOT NULL,
  `status_pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_pedido_status_pedido1_idx` (`status_pedido_id` ASC),
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `estruturart`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_status_pedido1`
    FOREIGN KEY (`status_pedido_id`)
    REFERENCES `estruturart`.`status_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(9) NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` TEXT NULL,
  `cidade_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pedido_id`),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC),
  INDEX `fk_endereco_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_endereco_pedido1_idx` (`pedido_id` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `estruturart`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `estruturart`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `estruturart`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`configuracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`configuracao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `field` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`log_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`log_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_inclusao` DATE NULL,
  `status_pedido_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_log_pedido_status_pedido1_idx` (`status_pedido_id` ASC),
  INDEX `fk_log_pedido_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_log_pedido_status_pedido1`
    FOREIGN KEY (`status_pedido_id`)
    REFERENCES `estruturart`.`status_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_pedido_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `estruturart`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`status_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`status_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`status_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`status_modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `descricao` TEXT NOT NULL,
  `largura_padrao` FLOAT NOT NULL,
  `altura_padrao` FLOAT NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `preco_pintura` FLOAT NULL,
  `porcentagem_acrescimo` FLOAT NOT NULL,
  `data_inclusao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `qtd_dias_producao` INT NOT NULL,
  `status_modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelo_status_modelo1_idx` (`status_modelo_id` ASC),
  CONSTRAINT `fk_modelo_status_modelo1`
    FOREIGN KEY (`status_modelo_id`)
    REFERENCES `estruturart`.`status_modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`pedido_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`pedido_itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `largura` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `data_inclusao` DATE NOT NULL,
  `quantidade` INT NULL DEFAULT 1,
  `status_item_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_itens_status_item1_idx` (`status_item_id` ASC),
  INDEX `fk_pedido_itens_pedido1_idx` (`pedido_id` ASC),
  INDEX `fk_pedido_itens_modelo1_idx` (`modelo_id` ASC),
  CONSTRAINT `fk_pedido_itens_status_item1`
    FOREIGN KEY (`status_item_id`)
    REFERENCES `estruturart`.`status_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_itens_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `estruturart`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_itens_modelo1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `estruturart`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`lancamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`lancamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` FLOAT NOT NULL,
  `preco_pintura` FLOAT NULL,
  `data_inclusao` DATE NOT NULL,
  `descricao` TEXT NULL,
  `desconto` FLOAT NULL,
  `usuario_id` INT NOT NULL,
  `pedido_itens_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lancamento_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_lancamento_pedido_itens1_idx` (`pedido_itens_id` ASC),
  CONSTRAINT `fk_lancamento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `estruturart`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_pedido_itens1`
    FOREIGN KEY (`pedido_itens_id`)
    REFERENCES `estruturart`.`pedido_itens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`pedido_itens_fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`pedido_itens_fotos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caminho_arquivo` VARCHAR(255) NOT NULL,
  `data_inclusao` DATE NOT NULL,
  `observacao` TEXT NULL,
  `pedido_itens_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_itens_fotos_pedido_itens1_idx` (`pedido_itens_id` ASC),
  CONSTRAINT `fk_pedido_itens_fotos_pedido_itens1`
    FOREIGN KEY (`pedido_itens_id`)
    REFERENCES `estruturart`.`pedido_itens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`status_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`status_material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`unidade_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`unidade_medida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `data_inclusao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NOT NULL,
  `data_inclusao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `materia_prima` INT(1) NULL DEFAULT 0,
  `status_material_id` INT NOT NULL,
  `unidade_medida_id` INT NOT NULL,
  `fornecedor_id` INT NOT NULL,
  `preco` FLOAT(9,2) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_material_status_material1_idx` (`status_material_id` ASC),
  INDEX `fk_material_unidade_medida1_idx` (`unidade_medida_id` ASC),
  INDEX `fk_material_fornecedor1_idx` (`fornecedor_id` ASC),
  CONSTRAINT `fk_material_status_material1`
    FOREIGN KEY (`status_material_id`)
    REFERENCES `estruturart`.`status_material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_unidade_medida1`
    FOREIGN KEY (`unidade_medida_id`)
    REFERENCES `estruturart`.`unidade_medida` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_material_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `estruturart`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`modelo_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`modelo_material` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_inclusao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `material_id` INT NOT NULL,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `material_id`, `modelo_id`),
  INDEX `fk_modelo_material_material1_idx` (`material_id` ASC),
  INDEX `fk_modelo_material_modelo1_idx` (`modelo_id` ASC),
  CONSTRAINT `fk_modelo_material_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `estruturart`.`material` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelo_material_modelo1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `estruturart`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estruturart`.`log_error`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estruturart`.`log_error` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `descricao` TEXT NULL,
  `data_inclusao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
